apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: xo9-honorport-heist-networkpolicy
spec:
  podSelector:
    matchLabels:
      app: xo9-honorport-heist
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from: []
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 2222
  egress:
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
