apiVersion: v1
kind: ResourceQuota
metadata:
  name: xo9-honorport-heist-quota
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "512Mi"
    limits.cpu: "1000m"
    limits.memory: "1Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: xo9-honorport-heist-limits
spec:
  limits:
    - default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      type: Container
